USE ETRADE4;
-- SELECT USERS.NAMESURNAME,ADDRESS.ADDRESSTEXT FROM USERS,ADDRESS WHERE USERS.ID=ADDRESS.USERID AND USERS.ID='1';
-- SELECT * FROM ADDRESS WHERE USERID='1';

-- SELECT U.NAMESURNAME AS ISIM,A.ADDRESSTEXT ADRES,C.COUNTRY,CT.CITY,T.TOWN,D.DISTRICT 
-- FROM USERS AS U,ADDRESS A,COUNTRIES C,CITIES CT,TOWNS T,DISTRICTS D
-- WHERE U.ID=A.USERID AND A.COUNTRYID=C.ID AND A.CITYID=CT.ID AND A.TOWNID=T.ID AND A.DISTRICTID=D.ID 
-- AND U.ID='1';

-- SELECT U.NAMESURNAME AS ISIM,COUNT(A.ID),COUNT(DISTINCT C.ID) AS SEHIRSAYISI 
-- FROM USERS AS U,ADDRESS A,COUNTRIES C,CITIES CT,TOWNS T,DISTRICTS D
-- WHERE U.ID=A.USERID AND A.COUNTRYID=C.ID AND A.CITYID=CT.ID AND A.TOWNID=T.ID AND A.DISTRICTID=D.ID
-- GROUP BY U.NAMESURNAME 
-- HAVING COUNT(A.ID)>2
-- ORDER BY U.NAMESURNAME;

SELECT CT.CITY,COUNT(U.ID),COUNT(DISTINCT T.ID)
FROM USERS AS U,ADDRESS A,COUNTRIES C,CITIES CT,TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND A.COUNTRYID=C.ID AND A.CITYID=CT.ID AND A.TOWNID=T.ID AND A.DISTRICTID=D.ID
GROUP BY CT.CITY
;