USE ETRADE2;
-- SELECT CAST(DATE_ AS DATE),SUM(TOTALPRICE) FROM SALES WHERE CITY='Ankara' GROUP BY CAST(DATE_ AS DATE) ORDER BY CAST(DATE_ AS DATE);
-- SELECT CITY,SUM(TOTALPRICE) FROM SALES WHERE CAST(DATE_ AS DATE)='2019-01-01' GROUP BY CITY ORDER BY SUM(TOTALPRICE) DESC LIMIT 10;
-- SELECT CITY,MONTH(CAST(DATE_ AS DATE)),COUNT(TOTALPRICE) FROM SALES WHERE CITY='Ankara' GROUP BY MONTH(CAST(DATE_ AS DATE)),CITY ORDER BY CITY ASC,COUNT(TOTALPRICE) DESC;
SELECT * FROM SALES LIMIT 1;
-- SELECT CATEGORY1,CATEGORY2,CATEGORY3,SUM(AMOUNT) FROM SALES GROUP BY CATEGORY1,CATEGORY2,CATEGORY3 ORDER BY CATEGORY1,CATEGORY2,CATEGORY3;
-- SELECT CITY,COUNT(DISTINCT(CUSTOMERCODE)) FROM SALES GROUP BY CITY ORDER BY CITY;
SELECT CITY,SUM(TOTALPRICE) FROM SALES GROUP BY CITY HAVING SUM(TOTALPRICE)>6000 ORDER BY SUM(TOTALPRICE) DESC ;