USE ETRADE4;

-- SELECT U.NAMESURNAME,A.ADDRESSTEXT,C.COUNTRY,CT.CITY,T.TOWN,D.DISTRICT 
-- FROM USERS U 
-- JOIN ADDRESS A ON U.ID=A.USERID
-- JOIN COUNTRIES C ON C.ID=A.COUNTRYID
-- JOIN CITIES CT ON CT.ID=A.CITYID
-- JOIN TOWNS T ON T.ID=A.TOWNID
-- JOIN DISTRICTS D ON D.ID=A.DISTRICTID
-- WHERE U.ID='1';

SELECT CT.CITY,COUNT(U.ID)
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
GROUP BY CT.CITY
;