-- CREATE DATABASE ETRADE3;
USE ETRADE3;
-- CREATE TABLE USERS (ID INT NOT NULL AUTO_INCREMENT,USERNAME_ VARCHAR(50),PASSWORD_ VARCHAR(50),NAMESURNAME VARCHAR(50)
-- ,EMAIL VARCHAR(100),GENDER VARCHAR(1),BIRTHDATE DATE, CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(ID));
-- ALTER TABLE USERS ADD TELNR1 VARCHAR(15), ADD TELNR2 VARCHAR(15);
-- CREATE TABLE ADDRESS(ID INT NOT NULL AUTO_INCREMENT,USERID INT,PRIMARY KEY(ID)
-- ,FOREIGN KEY(USERID) REFERENCES USERS(ID),COUNTRYID TINYINT,CITYID SMALLINT,TOWNID INT,DISTRICTID INT
-- ,POSTALCODE VARCHAR(50),ADDRESSTEXT VARCHAR(50));
-- CREATE TABLE COUNTRIES(ID INT NOT NULL AUTO_INCREMENT,PRIMARY KEY(ID),COUNTRY VARCHAR(50));
-- ALTER TABLE COUNTRIES MODIFY COLUMN ID TINYINT NOT NULL AUTO_INCREMENT;
-- ALTER TABLE ADDRESS ADD FOREIGN KEY(COUNTRYID) REFERENCES COUNTRIES(ID);
DESCRIBE ADDRESS;
-- CREATE TABLE CITIES(ID SMALLINT NOT NULL AUTO_INCREMENT,PRIMARY KEY (ID),CITY VARCHAR (50));
-- ALTER TABLE ADDRESS ADD FOREIGN KEY(CITYID) REFERENCES CITIES(ID);