-- SELECT ASCII('A');
-- SELECT CHAR(65);
-- SELECT CHAR(ASCII('B'));

USE ETRADE4;
-- SELECT COUNT(*) FROM USERS WHERE USERNAME_ LIKE 'O%';
-- SELECT COUNT(*) FROM USERS WHERE SUBSTRING(USERNAME_,1,1)='O';

-- SELECT COUNT(*) FROM USERS WHERE USERNAME_ LIKE '%O';
-- SELECT COUNT(*) FROM USERS WHERE SUBSTRING(USERNAME_,LENGTH(USERNAME_),1)='O';

-- SELECT POSITION('UC' IN 'YUCEL');

-- SELECT LEFT('YUCEL',3);
-- SELECT RIGHT('YUCEL',2);
-- SELECT LEFT('YUCEL AYDIN',POSITION(' ' IN 'YUCEL AYDIN'));
-- SELECT RIGHT('YUCEL AYDIN',LENGTH('YUCEL AYDIN')-POSITION(' ' IN 'YUCEL AYDIN'));

-- SELECT LTRIM(' YUCEL ');
-- SELECT RTRIM(' YUCEL ');
-- SELECT TRIM(' YUCEL ');

SELECT UPPER('yucel');
SELECT LOWER('YUCEL');
SELECT REVERSE('YUCEL');
SELECT CONCAT('178',REPEAT('0',8-LENGTH('178')));
SELECT CONCAT('1780',REPEAT('0',8-LENGTH('1780')));
SELECT CONCAT('17800',REPEAT('0',8-LENGTH('17800')));